Add schema based in a diagram file to database design
rica213/vet_clinic pull request #6
Opened 2023-04-11 15:41 UTC by coderacheal

### **In this pull request,**

- [ ] Create a new database called clinic
- [ ] Add new tables to the database
- [ ] Create a bridge table for the many-to-many relationship

2023-04-11 16:09 UTC, christianbiring1 requested changes
Hi @coderacheal @rica213, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/231223605-00d0db33-7acf-459b-9590-7db02e5beff2.gif)

## Highlights
- [ ] The table has been created correctly :+1: 
- [ ] The many-to-many relationship between medical_history and treatment has been implemented properly :+1: 
- [ ] Descriptive PR `title` and `summary` :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 16:09 UTC, christianbiring1 commented on schema_based_on_diagram.sql
> +    id INT PRIMARY KEY,
[OPTIONAL]
- [ ] To make sure the id is incrementing automatically, You may consider saying
```sql
id int SERIAL PRIMARY KEY
```

2023-04-11 16:09 UTC, christianbiring1 commented on schema_based_on_diagram.sql
> +    id INT PRIMARY KEY,
[OPTIONAL]
- [ ] Since this is a join table that allows us to make the many-to-many relationship works, there's no need for it to have the id column.

2023-04-11 16:09 UTC, christianbiring1 commented on schema_based_on_diagram.sql
> +    id INT PRIMARY KEY,
- [ ] Also the code base can be refactor like so:

```sql
CREATE TABLE medical_histories_has_treatments (
    medical_history_id int references medical_histories(id),
    treatment_id int references treatments(id),
    );

```

2023-04-11 16:09 UTC, christianbiring1 commented on schema_based_on_diagram.sql
> +)
- [ ] Kindly make sure all the foreign keys have indexes as specified in the project requirements.
Hint: The index can be created like so:
```sql
CREATE INDEX ON medical_histories (patient_id);
-- and so on, I mean on all the foreign keys --
```

2023-04-12 07:58 UTC, arslanbisharat commented
Hi @coderacheal,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 08:04 UTC, merged